name: Build Dockerfile linux/arm64,linux/amd64

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build_options:
        type: string
      
    secrets:
      docker_user:
        required: true
      docker_password:
        required: true



jobs:
  build_and_push:
    name: Push Docker image to multiple arch in registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & Push to Docker Hub amd64(x86)
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          tags: {{ inputs.tags }}
          push: true
          build-args: |
            RUNNER_VERSION=${{ steps.extract_branch_name.outputs.runner_version }}